### PR TITLE
Fixing stat table issues

### LINKED ISSUE #193: Listing/naming of weights in MS office
UPDATE
I've got these to work now in PowerPoint by using v.1.08 and by only installing the ttf files from the Web fonts folder (the OTFs won't install on my Mac or any of my colleagues). Please can I add a request? It wasn't clear to me which version was in the fonts folder in this repository – please can you add the version number to the folder name?
_____

Hi
My first post here, so hope I've done this correctly!

I'm trying to use Public Sans in MS Office on a Mac. It doesn't seem to be displaying the weight names correctly. See this screengrab:
Screenshot 2021-04-06 at 17 17 14
The different weights do work, but obviously it's trial and error trying to figure out which is the right weight!

I'm using version 1.007 downloaded from Google Fonts. I'm using the static TTF version.

I also removed the TTF version and tried the Variable version, which yielded this result:
Screenshot 2021-04-06 at 17 43 14

I also downloaded the OTF version from here, but my Mac wouldn't install it, citing critical errors as the reason.

MS Word is v16.37 and is up to date (as of just now).

The typeface works perfectly in Adobe CC Indesign.

Can you help? Sorry if this is user error!

### PR DESCRIPTION
**Pull request by aaronbell**
This update adds `gftools gen-stat` to the build process, as well as a stat.yaml file that `gen-stat` uses to add the proper stat table. Validated that everything works as expected in MS Mac Word. 

Closes #193

### CODE REVIEW

**Comment by aaronbell** [comment]
If you merge this in, I can push an update to GF with the proper STAT table :)

**Comment by davelab6** [comment]
@thisisdano please could you take a look at this? :)

**Comment by thisisdano** [comment]
@davelab6 Next on my list — just needs merge with our updates to the build process

**Comment by thisisdano** [comment]
Merging to an internal work branch to finish the merge to `develop`

**Pull request merged**
