### PR TITLE
Add ʻokina character

### LINKED ISSUE #35: Missing Hawaiian Character: ʻ
The font has support for most of the Hawaiian Diacritics (ĀāĪīŪūĒēŌō) but is missing the [ʻokina](https://en.wikipedia.org/wiki/%CA%BBOkina).

````Ā ā Ī ī Ū ū Ē ē Ō ō ʻ````

"the ʻokina is encoded as U+02BB ʻ MODIFIER LETTER TURNED COMMA, which can be rendered in HTML by the entity &#699; (or in hexadecimal form &#x02BB;)"

Should look similar to a left single quote but able to be told apart from the punctuation. Much like [this example from Wikipedia](https://en.wikipedia.org/wiki/%CA%BBOkina#/media/File:Okina-using-Linux-Libertine.svg). 

There are currently less than 30 fonts that support all the Hawaiian Characters on Google fonts, This font being available would greatly help Government sites.

### PR DESCRIPTION
**Pull request by thisisdano**
[Preview](https://federalist-proxy.app.cloud.gov/preview/uswds/public-sans/dw-add-okina/)
> Test by heading to this page, then inspecting and modifying any text to add `Hawai&#699;i`.

Adding a Hawaiian `ʻokina` character.
- adds `commaturnedmod` char
- updates `apostrophemod` char to  match `commaturnedmod`, but rotated

Test:
Screen Shot 2019-04-09 at 3 00 56 PM

Fixes #35.

### CODE REVIEW

**Comment by thisisdano** [comment]
@ian4uh Am I on the right track here? I'm not certain how much smaller it should be (if at all) from the single quote characters. I'm also a bit unsure about its vertical position. Does this look too high, too low, or ok?

Screen Shot 2019-04-09 at 9 35 23 AM
Screen Shot 2019-04-09 at 9 35 33 AM
Screen Shot 2019-04-09 at 9 35 50 AM

**Comment by thisisdano** [comment]
Updated:
Screen Shot 2019-04-09 at 11 50 39 AM
Screen Shot 2019-04-09 at 11 51 02 AM
Screen Shot 2019-04-09 at 11 51 42 AM

**Comment by ian4uh** [comment]
Sorry wasn't online much yesterday. Kinda late to the game. 

Definitely on the right track. The lower and rounded top is very good for differentiation. main thing is trying to keep that 6 shape. 

Thanks for your hard work~

**Comment by thisisdano** [comment]
Thanks Ian!

**Pull request merged**
